MostarConstruct/Areas/Administracija/Controllers/GradoviController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MostarConstruct.Data;
using MostarConstruct.Models;
using MostarConstruct.Web.Areas.Administracija.ViewModels;
using MostarConstruct.Web.Helper;
using MostarConstruct.Web.Helper.IHelper;

namespace MostarConstruct.Web.Areas.Administracija.Controllers
{

    [Area(nameof(Administracija))]
    [Autorizacija(false, TipKorisnika.Administrator)]
    public class GradoviController : Controller
    {
        #region DI
        private DatabaseContext db;
        private IDropdown dd;
        public int PageSize = 4;

        public GradoviController(DatabaseContext db, IDropdown dd)
        {
            this.db = db;
            this.dd = dd;
        }
        #endregion

        #region Index
        public IActionResult Index(int page = 1)
        {
            GradoviIndexViewModel vm = new GradoviIndexViewModel()
            {
                Rows = db.Gradovi.Select(x => new GradoviIndexViewModel.Row()
                {
                    GradId = x.GradID,
                    Drzava = x.Regija.Drzava.Naziv,
                    Naziv = x.Naziv,
                    Regija = x.Regija.Naziv,
                    PostanskiBroj = x.PostanskiBroj
                }).OrderBy(x => x.GradId).Skip((page - 1) * PageSize).Take(PageSize).ToList(),
                PagingInfo = new Web.ViewModels.PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = db.Gradovi.Count()
                }
            };

            return View(vm);
        }
        #endregion

        #region Add
        public IActionResult Dodaj() => PartialView("_Dodaj", GetDefaultViewModel(new GradoviDodajViewModel()));

        [HttpPost]
        public IActionResult Dodaj(GradoviDodajViewModel vm)
        {
            //if (!ModelState.IsValid)
            //{              
            //    return PartialView("_Dodaj", GetDefaultViewModel(vm));
            //}

            db.Gradovi.Add(vm.Grad);
            db.SaveChanges();

            return Json(new { success = true });
        }

        #endregion

        #region Edit
        public IActionResult Uredi(int gradId) => PartialView("_Uredi", GetDefaultViewModel(new GradoviUrediViewModel() { Grad = db.Gradovi.Find(gradId) }));

        [HttpPost]
        public IActionResult Uredi(GradoviUrediViewModel vm)
        {
            if (!ModelState.IsValid)
                return PartialView("_Uredi", GetDefaultViewModel(vm));

            db.Gradovi.Update(vm.Grad);
            db.SaveChanges();

            return Json(new { success = true });
        }
        #endregion

        #region Delete
        [HttpPost]
        public IActionResult Obrisi(int gradId)
        {
            db.Gradovi.Remove(db.Gradovi.Find(gradId));
            db.SaveChanges();
            return RedirectToAction(nameof(Index), new { page = 1 });
        }
        #endregion

        #region Helpers
        private GradoviDodajViewModel GetDefaultViewModel(GradoviDodajViewModel vm)
        {
            vm.Grad = vm.Grad ?? new Grad();
            vm.Regije = vm.Regije ?? dd.Regije().ToList();

            return vm;
        }

        private GradoviUrediViewModel GetDefaultViewModel(GradoviUrediViewModel vm)
        {
            vm.Grad = vm.Grad ?? new Grad();
            vm.Regije = vm.Regije ?? dd.Regije().ToList();

            return vm;
        }

        public JsonResult GetGradoviByRegijaId(int regijaId)
        {
            List<SelectListItem> gradovi = dd.Gradovi(regijaId).ToList();
            return Json(gradovi);
        }
        #endregion
    }
}

MostarConstruct/Areas/Administracija/Views/Gradovi/Index.cshtml
@model GradoviIndexViewModel
@{
    ViewData["Title"] = "Index";
}
<section id="main-content">
    <section class="wrapper">
        <div class="panel">
            <div class="panel-heading">
                <h3>Lista gradova</h3>
                
            </div>
            <div class="panel-body">
                <div class="pull-right">
                    <button type="button" class="btn btn-primary btnAdd"><i class="fa fa-plus"></i> Dodaj</button>
                </div>
                <br />
                <br />
                <br />

                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Naziv</th>
                            <th>Postanski broj</th>
                            <th>Regija</th>
                            <th>Drzava</th>
                            <th>Akcije</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var grad in Model.Rows)
            {
                <tr>
                    <td>@grad.Naziv</td>
                    <td>@grad.PostanskiBroj</td>
                    <td>@grad.Regija</td>
                    <td>@grad.Drzava</td>
                    <td>
                        <form asp-action="Obrisi" method="post">
                            <button type="button" class="btn btn-info btnEdit" idValue="@grad.GradId"><i class="fa fa-pencil"></i> Uredi</button>
                            <input name="gradId" value="@grad.GradId" hidden />
                            <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i> Obriši</button>
                        </form>
                    </td>
                </tr>
}
                    </tbody>
                </table>

                <div class="row">
                    <div class="col-md-12">
                        <div page-model="@Model.PagingInfo" page-action="Index" page-classes-enabled="true"
                             page-class="btn" page-class-normal="btn-default"
                             page-class-selected="btn-primary" class="btn-group pull-right">
                        </div>
                    </div>
                </div>

                <div id="ajaxDiv">

                </div>

            </div>
        </div>
    </section>
</section>

<script>
    $(function () {

        $(".btnAdd").click(function () {
            $.get("@Url.Action("Dodaj", "Gradovi")", function (data) {
                $("#ajaxDiv").html(data);
            });
        });

        $(".btnEdit").click(function () {

            var id = $(this).attr("idValue");


            $.ajax({
                url: "@Url.Action("Uredi", "Gradovi")",
                type: "GET",
                data: { gradId: id },
                success: function (data) {
                    $("#ajaxDiv").html(data);
                }
            });
        });

    });
</script>

MostarConstruct/Areas/Administracija/Views/Gradovi/_Dodaj.cshtml
@model GradoviDodajViewModel
<form id="forma">   
    <div class="form-group">
        <label asp-for="Grad.Naziv">Naziv:</label>
        <input asp-for="Grad.Naziv" class="form-control" />
        <div><span asp-validation-for="Grad.Naziv" class="text-danger"></span></div>
    </div>

    <div class="form-group">
        <label asp-for="Grad.PostanskiBroj">Postanski broj:</label>
        <input asp-for="Grad.PostanskiBroj" class="form-control" />
        <div><span asp-validation-for="Grad.PostanskiBroj"></span></div>
    </div>

    <div class="form-group">
        <label asp-for="Grad.RegijaID">Regija:</label>
        <select asp-for="Grad.RegijaID" asp-items="Model.Regije" class="form-control"></select>
    </div>

    <div class="pull-right">
        <button type="button" class="btn btn-primary btnSubmit"><i class="fa fa-save"></i> Sačuvaj</button>
        <button type="button" class="btn btn-default btnCancel"><i class="fa fa-times-circle"></i> Odustani</button>
    </div>
</form>
<script>

    $(".btnSubmit").click(function () {

        var forma = $("#forma");

        $.ajax({
            url: "@Url.Action("Dodaj", "Gradovi")",
            type: "POST",
            data: forma.serialize(),
            success: function (data) {
                if (data.success) {
                    window.location.href = "/Administracija/Gradovi/Index?page=1";
                }
            }
        });

    });

    $(".btnCancel").click(function () {
        window.location.href = "/Administracija/Gradovi/Index?page=1";
    });

</script>

MostarConstruct/Areas/Administracija/Views/Gradovi/_Uredi.cshtml
@model GradoviUrediViewModel
<form id="forma">
    <div class="form-body">
        <input asp-for="Grad.GradID" value="@Model.Grad.GradID" hidden />

        <div class="form-group">
            <label asp-for="Grad.Naziv">Naziv:</label>
            <input asp-for="Grad.Naziv" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="Grad.PostanskiBroj">Postanski broj:</label>
            <input asp-for="Grad.PostanskiBroj" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="Grad.RegijaID">Regija:</label>
            <select asp-for="Grad.RegijaID" asp-items="Model.Regije" class="form-control"></select>
        </div>

        <div class="pull-right">
            <button type="button" class="btn btn-primary btnSaveEdit"><i class="fa fa-save"></i> Sačuvaj</button>
            <button type="button" class="btn btn-default btnCancel"><i class="fa fa-times-circle"></i> Odustani</button>
        </div>
    </div>
</form>


<script>

    $(".btnSaveEdit").click(function () {
        var forma = $("#forma");

        $.ajax({
            url: "@Url.Action("Uredi", "Gradovi")",
            type: "POST",
            data: forma.serialize(),
            success: function (data) {
                if (data.success) {
                    window.location.href = "/Administracija/Gradovi/Index?page=1";
                }
            }
        });
    });

    $(".btnCancel").click(function () {
        window.location.href = "/Administracija/Gradovi/Index?page=1";
    });

</script>